add: 新規確認画面の追加
odlovesq/kakeibo-app pull request #5
Opened 2020-12-08 13:10 UTC by kabuki37

## やったこと
新規登録時の確認画面を追加しました
https://github.com/odlovesq/kakeibo-app/issues/1

<img width="33%" alt="スクリーンショット 2020-12-08 22 08 54" src="https://user-images.githubusercontent.com/15226533/101487882-27ca8100-39a2-11eb-95df-e37657579a1c.png">

2020-12-08 13:14 UTC, odlovesq commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +          :value="'*'.repeat(user.password.length)"
vuejsのfilter機能があるのでそれ使うといいかもしれないです
https://jp.vuejs.org/v2/guide/filters.html

2020-12-08 13:20 UTC, odlovesq commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +      <v-form ref="form" lazy-validation>
ここってformの必要ありますか??
必要なかったら直接v-card-actionsにしてもいいかもしれないです

2020-12-08 13:22 UTC, odlovesq commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +            class="white--text"
元がそうだったからっぽいですが、実は`white-text`とかだったりしませんか??
ハイフン2個なのがちょっと気になりました

2020-12-08 13:27 UTC, odlovesq commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +  name: 'App',
ルートコンポーネントじゃないのでAppという名前だとちょっと違和感がありました。
呼び出し元にあわせて`SignupConfirmation`とかでもいい気がします(それで動くかはわかりませんが…)

2020-12-08 13:27 UTC, odlovesq commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +      type: Object
バリデーション増やしても良い気がしました。
ユーザー情報がないと何も表示できないので、requireとか入れても良いかもしれないです

2020-12-08 13:48 UTC, odlovesq commented on kakeibo-front/components/signup/SignupInput.vue
> +      this.$emit('catchUserInfo', this.user);
メソッドの中がemitだけなら直接`@click`に書いても良い気がしました

2020-12-08 13:55 UTC, odlovesq commented on kakeibo-front/components/signup/SignupInput.vue
> +      this.$emit('catchUserInfo', this.user);
あと、catchするのは親なのでここでcatchHogeHogeイベントが発火するのに違和感がありました。
`confirmatin-button-click`とかいかがでしょうか?(emitするイベント名はケバブケースがよく見る気がしました)

2020-12-08 13:56 UTC, odlovesq commented on kakeibo-front/pages/signup.vue
> +
この空行削除でおねがいします

2020-12-08 14:01 UTC, odlovesq commented on kakeibo-front/pages/signup.vue
> +    saveUserInfo(user) {
saveだとDBに保存感あるので、setUserはいかがでしょうか?
Infoなくても通じる気がしたので外してみました

2020-12-08 14:04 UTC, odlovesq commented
@kabuki37 コメントしました!!確認おねがいします!!:bow:

2020-12-09 02:23 UTC, kabuki37 commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +            class="white--text"
公式では`white-text`になっていますが、`white--text`が正しいみたいです。
https://qiita.com/HorikawaTokiya/items/114cb92a9d1585e6c326

2020-12-13 03:05 UTC, kabuki37 commented on kakeibo-front/pages/signup.vue
> +    saveUserInfo(user) {
Userだけだと意味が変わる気がしたのでUserInfoのままにしてます。

2020-12-13 09:51 UTC, odlovesq commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +    passwordMask: function(val) {
アロー関数にしてほしいです :bow:

2020-12-13 10:02 UTC, odlovesq commented on kakeibo-front/components/signup/SignupInput.vue
> +    clickNextButton() {
clickだとクリックするためのメソッドっぽく感じるので、直接`emitConfirmationButtonClickEvent`とかでも良いかなと思いました

2020-12-13 10:03 UTC, odlovesq requested changes
@kabuki37 
追加でコメントしたので確認お願いします!!

2020-12-13 10:05 UTC, odlovesq commented on kakeibo-front/components/signup/SignupInput.vue
> +      this.$emit('catchUserInfo', this.user);
口頭でhtmlの部分で`this.$emit`できないからハンドラ用意すると伺ったのでそのままメソッドにしてて大丈夫です!!

2020-12-13 10:58 UTC, kabuki37 commented on kakeibo-front/components/signup/SignupConfirmation.vue
> +    passwordMask: function(val) {
変更しました！

2020-12-13 10:59 UTC, kabuki37 commented on kakeibo-front/components/signup/SignupInput.vue
> +    clickNextButton() {
口頭で確認取れたので`clickedNextButton`にしました

2020-12-13 11:03 UTC, odlovesq approved these changes
諸々対応ありがとうございます!!!
LGTMです!!!!

2020-12-15 09:19 UTC, merged